name: PR Title Format Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check PR title format
        id: check-title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;

            const ticketPattern = /^\[PCKDAAS-\d+\]:\s+.+$/;
            const naPattern = /^\[N\/A\]:\s+.+$/;
            const isValid = ticketPattern.test(title) || naPattern.test(title);


            if (!isValid) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: `❌ **Invalid PR Title Format**
                
                **Required format:**
                - \`[PCKDAAS-1234]: Brief description\`
                - \`[N/A]: Brief description\`

                Please update your PR title to match one of these patterns.`
              });
                        
            // Fail the check
            core.setFailed('PR title does not follow required format');
            } else {
             // remove comment if title is valid
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber
              });

              for (const comment of comments.data) {
                if (comment.body.includes('Invalid PR Title Format')) {
                  await github.rest.issues.deleteComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: comment.id
                  });
                }
              }
              console.log('PR title is valid');
            }
