name: Mark stale PRsAdd commentMore actions

on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: "0 9 * * *" # Runs 9 am UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          days-before-pr-stale: 5

          days-before-pr-close: 5 # another 5 days after being marked stale

          stale-pr-message: |
            🕐 **Stale PR Reminder**

            This PR has been inactive for 5 minutes. To keep the momentum going:

            - [ ] Review and address any feedback
            - [ ] Rebase if needed to resolve conflicts  
            - [ ] Add any missing tests or documentation
            - [ ] Request review if ready

            If this PR is no longer needed, please close it, or turn it into a draft.

            *Remove the stale label or add a comment to reset the timer.*

          stale-pr-label: "stale"

          exempt-pr-labels: "no-stale-check,keep-open,work-in-progress"

          exempt-draft-pr: true

          remove-stale-when-updated: true

          close-pr-message: |
            🗑️ **PR Closed**

            This PR has been inactive for 5 days and has been closed. If you still need this PR, please reopen it.
