name: Mark stale PRsAdd commentMore actions

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, unlabeled, edited]
  workflow_dispatch: # Allow manual triggering
  schedule:
    # Run every 20 minutes (for testing - adjust as needed)
    - cron: "*/20 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          # Mark PRs as stale after 5 minutes (1/288 of a day)
          # Note: GitHub Actions uses days as the unit, so 5 minutes = 5/1440 ≈ 0.0035 days
          days-before-pr-stale: 0.0035

          stale-pr-message: |
            🕐 **Stale PR Reminder**

            This PR has been inactive for 5 minutes. To keep the momentum going:

            - [ ] Review and address any feedback
            - [ ] Rebase if needed to resolve conflicts  
            - [ ] Add any missing tests or documentation
            - [ ] Request review if ready

            If this PR is no longer needed, please close it.

            *Remove the stale label or add a comment to reset the timer.*

          stale-pr-label: "stale"

          exempt-draft-pr: true

          # Don't auto-close stale PRs (set to -1)
          days-before-pr-close: 0.007

          close-pr-message: |
            🗑️ **PR Closed**

            This PR has been inactive for 10 minutes and has been closed. If you still need this PR, please reopen it.

          exempt-pr-labels: "no-stale-check,keep-open,work-in-progress"

          remove-stale-when-updated: true
